export { default as BasicModal } from './BasicModal'
export { default as FormWrapper } from './FormWrapper'
export { default as Loading } from './Loading'
export { default as LogoutBtn } from './LogoutBtn'
export { default as MainWrapper } from './MainWrapper'
export { default as Table } from './Table'
